### PR TITLE
[documentation site] Opening the sidebar on Meta + K

### PR DESCRIPTION
**Pull request by CapitaineToinon**
Fix for #860. I saw on contribution guide that I could open a pull request directly for modifications on the documentation website. Let me know if that's okay. 

These changes simply open the sidebar by checking the relevant checkbox whenever Meta + K is used. I also added an even listener to automatically close the sidebar whenever a search result is picked. Because the sidebar is always opened on desktop by using css, these changes only affect the small screen views.

Let me know if I should change anything.
Love daisyui but this issue was driving me crazy 👍

### CODE REVIEW

**Comment by CapitaineToinon** [comment]
Switched to using media query in Javascript to conditionally show the search input in the sidebar instead. That way, the sidebar won't listen to the Search events when the Search input isn't in the DOM anymore. Now as far as I can tell it works as expected. 

The source code of useMediaQuery and useBreakpoints are basically a direct copy of @vueuse's [useMediaQuery](https://vueuse.org/core/usemediaquery/) and [useBreakpoints](https://vueuse.org/core/usebreakpoints/). 

The only concern left I have is that according to tailwind's doc, importing the entire tailwind config in js will increase bundle size and that we should use something like [babel-plugin-preval](https://github.com/kentcdodds/babel-plugin-preval) to statically include the config we need in the code.

**Comment by saadeghi** [comment]
Hey.  
Thank you for the PR, but I'm not sure if the hotkeys are even necessary for the small screen.

**Comment by CapitaineToinon** [comment]
For mobile phones I agree but right now the search bar disappears at 1024px, which is quite big still. In my use case on my laptop, just having 2 browsers in split screens already hit that breakpoint.

**Comment by saadeghi** [comment]
Thank you 🙌

**Pull request merged**
