### PR TITLE
[Japanese] Improve theme page and drawer translation

### PR DESCRIPTION
**Pull request by tamagoez**
Fix mistake at theme page.
Also improve drawer content translation.

### CODE REVIEW

**Comment by tamagoez** [comment]
That's all

**Comment by saadeghi** [comment]
@tamagoez Thank you

**Comment by tamagoez** [comment]
Seems build failed

**Comment by saadeghi** [comment]
fixed https://github.com/saadeghi/daisyui/commit/f8ba9f57f78c0db51ef794693ad30fc0121f1c9e

**Comment by tamagoez** [comment]
Thank you very much

**Pull request merged**
