### PR TITLE
add basic implementation of toast component/utilities

### PR DESCRIPTION
**Pull request by cryptodeal**
Here's my super basic implementation of a toast component.

Would love feedback on the styles and and any help I can get on adding css animations as I'm just leveraging svelte/transitions when using my my other svelte projects at the moment. 

Additionally, I've added the corresponding routes/components/toast.svelte.md (published set to false), a Toast component, and a notification store (located in $lib/stores) to make a working click to add toast notification demo in the component doc page.

### CODE REVIEW

**Comment by ctwhome** [comment]
I love the fact that is it a full example for Svelte, but I don't think that it fits within Daisy UI since it is a CSS framework.
IT would be lovely to have a Svelte + DaisyUI lib components

**Comment by cryptodeal** [comment]
> I love the fact that is it a full example for Svelte, but I don't think that it fits within Daisy UI since it is a CSS framework.
> IT would be lovely to have a Svelte + DaisyUI lib components

I'd written the component per the architecture described by @saadeghi in the original Issue/Feature Request for snackbar/toast, "Yes, it should be something similar to an alert with position:fixed but I'm going to also add animations and a wrapper to stack multiple items on top of each other. Then all we need is a template loop (with Alpine, Vue, React, etc) to add/remove items in the wrapper." See: https://github.com/saadeghi/daisyui/issues/221#issuecomment-941270950

With that being said, if that isn't the route ya'll want to go, I can just remove the Toast component and associated notifications store, which would remove any reliance on svelte by removing the dynamic click to add toast demo.

**Comment by cryptodeal** [comment]
@saadeghi probably need feedback with regards to your thoughts on the current implementation of styles for the core toast component as well as the toast-control wrapper styles in order to make further updates and ensure I'm approaching this in a manner consistent with the design principles of the library.

Additionally, I'm happy to remove the svelte component and associated store I'd written to demo the template loop to add/remove toast items on click as it's reliant on a framework vs pure css.

**Comment by saadeghi** [comment]
Thanks for the PR.  
I will review it soon, but I think we should avoid framework-specific JS for the components.  

I appreciate your efforts for creating the functionality of adding/removing toasts using Svelte store but I think we should just provide the style and structure for daisyUI components.  
Adding and removing elements must be handled by the developers based on their needs (they might need permanent toast, timers, close buttons, etc.)

**Comment by cryptodeal** [comment]
No worries; I'd just copied the svelte implementation from another project, so didn't involve any added work on my part! I've updated the PR to remove the svelte implementation from the docs site.

**Comment by saadeghi** [comment]
Added in `2.19.0` version 🎉
Thank you @cryptodeal @ctwhome    

I applied some changes tho:  
This PR was suggesting very similar styles to `alert` component. Instead of that, I used `toast` class as the wrapper and it can contain `alert`, `card` or anything else. It just handles the positioning, stacking and animation.

**Pull request merged**
