### PR TITLE
`/docs/themes/` translation (also some other translation)

### PR DESCRIPTION
**Pull request by tamagoez**
https://daisyui.com/docs/themes/

### CODE REVIEW

**Comment by saadeghi** [comment]
`Translate` tag needs to be closed
```svelte
<Translate text="something" />
```

**Comment by tamagoez** [comment]
I forgotten to add it.

**Comment by tamagoez** [comment]
I don't know how should I mark
> \> this one

and
 - \- this one
 
to avoid #598 ?

**Comment by saadeghi** [comment]
Markdown quotes like [this](https://github.com/saadeghi/daisyui/blob/f0aff564f3e25eded53e40d6d9e1067e0ea5a75e/src/docs/src/routes/docs/themes.svelte.md?plain=1#L20) should be like:

```md
> <Translate text="string" />
```

And list items are the same
```md
- <Translate text="string" />
```

To make sure everything's okay, you can run the document site on local and see the result:
https://github.com/saadeghi/daisyui/blob/master/.github/CONTRIBUTING.md#to-run-the-documentation-site-on-local

**Comment by tamagoez** [comment]
Now, if I didn't make a mistake, only I need to do is translate.
I think it will take 24 hours to commit this pr.

**Comment by tamagoez** [comment]
It seems ready to pull.
I will not add any other translation in this PR.

**Comment by saadeghi** [comment]
Thank you @tamagoez. Really appreciated 👏

**Comment by tamagoez** [comment]
It's my pleasure!

**Pull request merged**
