### PR TITLE
Fixed `alert` components in `theme-generator`

### PR DESCRIPTION
**Pull request by TechGenius7777**
Fixed `alert` components in `theme-generator`

### CODE REVIEW

**Comment by TechGenius7777** [comment]
Should I create another pull request with only the bug fix and close this one?

**Comment by saadeghi** [comment]
> Should I create another pull request

You can do that.

Or you can add a new commit to this PR and revert changes of other files.

**Comment by TechGenius7777** [comment]
Done!

**Comment by TechGenius7777** [comment]
Now this pull request is ready to be merged from my side

**Comment by saadeghi** [comment]
Thank you

**Comment by TechGenius7777** [comment]
Thank You!

**Pull request merged**
