### PR TITLE
fix: #1366 add type for daisyui plugin

### PR DESCRIPTION
**Pull request by soorria**

### CODE REVIEW

**Comment by saadeghi** [comment]
Thank you!  
Let me know when this PR is ready to merge.

**Comment by saadeghi** [comment]
@soorria Is there anything I can help with?

Also, is the new `src/tailwind-config.d.ts` file in this PR necessary? Because I don't know how is it going to be used.

**Comment by soorria** [comment]
Hey, sorry I totally forgot about this. I'll fix it up tonight.

**Comment by saadeghi** [comment]
Thank you @soorria This is going to be very helpful for Typescript users

**Comment by hkbertoson** [comment]
Excited for this

**Comment by soorria** [comment]
fyi @saadeghi this is good to go when you're happy with it 😄

**Comment by saadeghi** [comment]
I was a little bit busy this week sorry. Will be merged by tomorrow. Thank you 💯

**Pull request merged**
