### PR TITLE
refactor color functions

### PR DESCRIPTION
**Pull request by gurgunday**
Oops, sorry for the mess, `git rebase` hates me 🤣

### CODE REVIEW

**Comment by saadeghi** [comment]
No problem. I should've mentioned before, that `v3` is a new (orphan) branch.  
Thank you 🙏

**Comment by saadeghi** [comment]
There's a problem. It's only generating the default theme.

**Comment by gurgunday** [comment]
Can you try again?

**Comment by gurgunday** [comment]
I also wanted to ask you about that if check...

Should it only apply the light theme if `false` is given, or should it act that way for any falsy value (like null)? For now, I tried to mimic the previous behavior

**Comment by saadeghi** [comment]
> Should it only apply the light theme if `false` is given, or should it act that way for any falsy value (like null)? For now, I tried to mimic the previous behavior

It should have the the exact same behavior as before: https://daisyui.com/docs/themes/#-2  
Because otherwise it would suddenly change every project that is using daisyUI and they have a specific config for their themes. I don't want to make breaking changes unless it's really necessary.

**Comment by gurgunday** [comment]
Ok, now `injectThemes` behaves exactly the same way as before

**Comment by polyzen** [comment]
> No problem. I should've mentioned before, that `v3` is a new (orphan) branch. Thank you pray

Why an orphan branch?

**Comment by saadeghi** [comment]
To reduce the repo size. It was getting huge (almost 1.5GB) because of huge git history.

**Comment by polyzen** [comment]
I'm not entirely against that, but this is a good read:
https://www.mail-archive.com/dri-devel@lists.sourceforge.net/msg39091.html

**Comment by saadeghi** [comment]
> I'm not entirely against that, but this is a good read: https://www.mail-archive.com/dri-devel@lists.sourceforge.net/msg39091.html

Thank you. I'm not going to erase anything, it's just a new branch. The problem is daisyUI repo changed a lot from version 0.x to 1.x and then 2.x and the repo also includes the docs site which was Nuxt at a point, then it changed to SvelteKit 0.x and now SvelteKit 1.x A lot of git history is really unnecessary to keep in the default branch, specially for people who want to fork and run the repo. The full history will be available of course on the other branch.

**Pull request merged**
