### PR TITLE
Feature: add "table-active" utility

### PR DESCRIPTION
**Pull request by efnninja**

### CODE REVIEW

**Comment by saadeghi** [comment]
@efnninja Thanks. This changes the background color of every `td` inside `table-active`.   
I'm not sure when this could be useful. Can you explain more please?

**Comment by efnninja** [comment]
Hi !
imagine you want to select a user or post to delete and you have checkbox buttons for multi deleting 
this time  `table-active ` can help to show the selected rows

**Comment by saadeghi** [comment]
@efnninja In that case we would need `tr` to have an `active` class. I will add this class today:
```html
<tr class="active">
```
I have to close this PR tho. Because it doesn't highlight one row. It will highlight **all** rows on a `<table>` with `table-active` class

**Comment by efnninja** [comment]
Ok !
Thanks.

**Comment by saadeghi** [comment]
@efnninja Added in version `1.9.0`

**Pull request closed without merging**
