### PR TITLE
Docs: add accordion always open example

### PR DESCRIPTION
**Pull request by davidgaroro**
Add accordion example to use checkbox instead of radio inputs to keep accordion items open.

### CODE REVIEW

**Comment by saadeghi** [comment]
Thanks for the PR, but there are already examples for that:  
https://daisyui.com/components/collapse/#collapse-with-checkbox

[collapse](https://daisyui.com/components/collapse/#collapse-with-checkbox) and [accordion](https://daisyui.com/components/accordion/) are basically the same thing visually, we can use them with checkbox or radio input and if it uses radio input, only one item can be open which makes it an "accordion"

I know there are different terms and opinions about how to call them.  
In daisyUI they are using the same class name (`collapse`) because they are visually the same thing, How ever because of the way radio inputs work (only one radio input with the same name can be checked) it allows us to have multiple `collapse` items next to each other and opening one can close the others which makes it what we can call "accordion"

Otherwise, using a checkbox, they can be open separately and we put those examples [here](https://daisyui.com/components/collapse/#collapse-with-checkbox) as "collapse" because they can be collapsed regardless of the behavior of others.


Let me know if you have a question.

**Comment by davidgaroro** [comment]
Sorry, I'm new to using DaisyUI.

I've been adding DaisyUI components quickly and I didn't stop to read everything in detail.

You are right, according to the definition of accordion in DaisyUI "only one item can stay open at a time". 

However, as a newcomer, I missed a live demo of an accordion with the option to keep multiple sections open like they do in other frameworks:
- Bootstrap: https://getbootstrap.com/docs/5.3/components/accordion/#always-open
- Material UI: https://mui.com/material-ui/react-accordion/#introduction

I love DaisyUI and I just wanted to improve the user experience for those looking for this specific functionality and not have to go to the collapse section and figure out how to do it, as there is no real example either.

**Comment by saadeghi** [comment]
Thanks.  
About keeping an item open, simply checking the radio or the checkbox using `checked` attribute will do it (like the examples from MUI or Bootstrap you mentioned)

I would be happy to merge future PRs from you and I don't want this one to discourage you from future contribution.

Thanks 🙏

**Comment by davidgaroro** [comment]
I think the title of this pull request "Always open" is a bit confusing.

This PR only adds a new example of accordion (not always open) but with the option to keep several open at the same time:


The code of this PR is the same as the example [Accordion with arrow icon](https://daisyui.com/components/accordion/#accordion-with-arrow-icon) but replacing `type="radio"` by `type="checkbox"` and removing `name="my-accordion-2"`.

```html
<div class="collapse collapse-arrow bg-base-200">
  <input type="checkbox" />
  <div class="collapse-title text-xl font-medium">
    Click to show/hide content
  </div>
  <div class="collapse-content">
    <p>hello</p>
  </div>
</div>
```

I make this PR because because when I wanted to add an accordion with this functionality and went to the documentation, it was not clear to me if this was possible as there was no example like in the other frameworks.

**Comment by davidgaroro** [comment]
I think the title of this pull request "Always open" is a bit confusing.

This PR only adds a new example of accordion (not always open) but with the option to keep several open at the same time:


The code of this PR is the same as the example [Accordion with arrow icon](https://daisyui.com/components/accordion/#accordion-with-arrow-icon) but replacing `type="radio"` by `type="checkbox"` and removing `name="my-accordion-2"`.

```html
<div class="collapse collapse-arrow bg-base-200">
  <input type="checkbox" />
  <div class="collapse-title text-xl font-medium">
    Click to show/hide content
  </div>
  <div class="collapse-content">
    <p>hello</p>
  </div>
</div>
```

I made this PR because because when I wanted to add an accordion with this functionality and went to the documentation, it was not clear to me if this was possible as there was no example like in the other frameworks.

**Comment by davidgaroro** [comment]
I think the title of this pull request "Always open" is a bit confusing.

This PR only adds a new example of accordion (not always open) but with the option to keep several open at the same time:


The code of this PR is the same as the example [Accordion with arrow icon](https://daisyui.com/components/accordion/#accordion-with-arrow-icon) but replacing `type="radio"` by `type="checkbox"` and removing `name="my-accordion-2"`.

```html
<div class="collapse collapse-arrow bg-base-200">
  <input type="checkbox" />
  <div class="collapse-title text-xl font-medium">
    Click to show/hide content
  </div>
  <div class="collapse-content">
    <p>hello</p>
  </div>
</div>
```

I made this PR because when I wanted to add an accordion with this functionality and went to the documentation, it was not clear to me if this was possible as there was no example like in the other frameworks.

Adding this example to the accordion documentation would be great.

**Comment by davidgaroro** [comment]
@saadeghi I think the title of this pull request "Always open" is a bit confusing.

This PR only adds a new example of accordion (not always open) but with the option to keep several open at the same time:


The code of this PR is the same as the example [Accordion with arrow icon](https://daisyui.com/components/accordion/#accordion-with-arrow-icon) but replacing `type="radio"` by `type="checkbox"` and removing `name="my-accordion-2"`.

```html
<div class="collapse collapse-arrow bg-base-200">
  <input type="checkbox" />
  <div class="collapse-title text-xl font-medium">
    Click to show/hide content
  </div>
  <div class="collapse-content">
    <p>hello</p>
  </div>
</div>
```

I made this PR because when I wanted to add an accordion with this functionality and went to the documentation, it was not clear to me if this was possible as there was no example like in the other frameworks.

Adding this example to the accordion documentation would be great.

**Pull request closed without merging**
