### PR TITLE
Adding default fade for toast

### PR DESCRIPTION
**Pull request by writeDavid**
Adding a default fade for a toast

### CODE REVIEW

**Comment by writeDavid** [comment]
You've stated that you don't want to impose logic with the library.  Maybe new var(s) for the pop and fade?

**Comment by saadeghi** [comment]
What does this animation do?  
Is it for when you hide/remove an item? Because that won't work. Hiding or removing is instant and it happens before the CSS animation.

**Comment by writeDavid** [comment]
When a toast is triggered, your pop animation runs.  It then waits 2.8 seconds, and then automatically fades it with the next animation (the added code).

**Comment by saadeghi** [comment]
First problem, It doesn't seem to work as you explained. It shows up with the `toast-pop` animation, then after `2.8s` it hides with the new `toast-fade` animation but immediately (as soon as animation ends - 0.25s) it becomes visible again.  

Second problem, what if someone doesn't want the toast to auto hide?  
Maybe they want it to be closed on click or using a JS timer.  
I think if we're adding something like this, it should be with new class like `auto-hide`

**Comment by writeDavid** [comment]
> Second problem, what if someone doesn't want the toast to auto hide? Maybe they want it to be closed on click or using a JS timer. I think if we're adding something like this, it should be with new class like `auto-hide`

The code was pulled from a working implementation, that handles toasts via a svelte store, so apologies I didn't forsee the issue.  I'll close this, because you're right, this type of request is better left to project implementors.

Thank you for the feedback!

**Pull request closed without merging**
