### PR TITLE
React tab for code snippets

### PR DESCRIPTION
**Pull request by WickedInvi**
Updated all components and tested snippets that might be problematic. Everything works fine.

### CODE REVIEW

**Comment by WickedInvi** [comment]
mockup-code changes need to be discarded.

**Comment by WickedInvi** [comment]
Due to the script, there was an issue with mockup-code.svelte.md. The issue is due to the using the pre tags as start and finish points.
Here is the fixed file. 
[mockup-code.svelte.md](https://github.com/saadeghi/daisyui/files/9380397/mockup-code.svelte.md)

**Comment by saadeghi** [comment]
Awesome!   
I will merge this after making sure all examples are okay.

**Comment by saadeghi** [comment]
@WickedInvi Thanks for the effort.  
Everything looks fine except:
1. `mockup-code.svelte.md` issue as you said:  
    Please add the file changes you mentioned to the PR.
3. a few other JSX syntaxes that must be replaced:  
    1. numerical values like this `tabindex="0"` ➡ `tabindex={0}`
    2. All SVG atrributes must be camelCase like this`stroke-linecap` ➡ `strokeLinecap` [[Full list here](https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes)]

It would be cool to automate this process using a script like the one you provided but since this is a one-time job and we don't need to translate HTML to JSX for all examples every time, I think we can just merge this PR (after fixes) and for new additional component examples, we will provide JSX code as well as HTML code.

**Comment by WickedInvi** [comment]
I've updated the mockup-code.svelte.md and added the JSX syntax

**Comment by chazzox** [comment]
is the `htmlFor=''` attribute an alternative to `for=''` in just react? just an observation that the  `for=""` attribute remains at. not sure if 
- https://daisyui.com/components/modal/ in the jsx template
and possibly some other places.

happy to make a pr :)

**Comment by saadeghi** [comment]
@chazzox nice catch! Yes, PRs are welcome of course.

**Comment by chazzox** [comment]
hopefully this catches everything :) https://github.com/saadeghi/daisyui/pull/1095

**Pull request merged**
