### PR TITLE
Feat/chat bubble

### PR DESCRIPTION
**Pull request by imanmalekian31**
New chat bubble component.

### CODE REVIEW

**Comment by imanmalekian31** [comment]
Is there any problem with this branch?
I would like to know if there is any problem to solve.

**Comment by saadeghi** [comment]
Nothing's wrong. It's awesome actually.
But I'm researching about different use cases to make sure it covers different design scenarios.  
I will apply a few changes and I will merge it this week.

**Comment by imanmalekian31** [comment]
Thank you for responding.

**Comment by ngladbach** [comment]
Hey, looking forward to use this! What is the current status? 🤗

**Comment by saadeghi** [comment]
Added in version `2.42.0` 🎉 

Thank you @imanmalekian31 

Sorry it took a long time but I had to make sure it can covers different use cases. Many things are changed compared to this PR for an easier syntax and more flexibility.

**Pull request merged**
