### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by StaticFX**
Some words were translated to literal. The word "Store" in german, was translated as "to save". And the word "Theme" can be translated to the word "Thema" but, the word "Design" fits better in this context.

### CODE REVIEW

**Comment by StaticFX** [comment]
That is true about design. Something like "Farbpalette" which would translate to colorpalette could also be a fitting word. Thema is more often used as "subject" instead of the actual theme of something.

**Comment by saadeghi** [comment]
Let's use `Farbpalette` then.

**Comment by StaticFX** [comment]
I have adjusted it in the correct places in my opinion

**Comment by saadeghi** [comment]
Thanks @StaticFX

**Pull request merged**
